# Source: https://savaslabs.com/2016/10/25/deploy-jekyll-with-travis.html

language: ruby
rvm:
 - 2.3.3

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
install:
  - bundle install

script: bash ./scripts/cibuild.sh

# Branch whitelist, only for GitHub Pages
branches:
  only:
  - source

# Keep Travis from testing `master` branch
branches:
  except:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build

deploy:
  provider: script
  script: bash ./scripts/deploy.sh
  skip_cleanup: true
  on:
    branch: source
